CREATE DATABASE TennisScoreboard;
USE TennisScoreboard;

CREATE TABLE Players(
ID int PRIMARY KEY NOT NULL,
Name varchar(55)
);

CREATE TABLE Matches(
ID int PRIMARY KEY NOT NULL,
Player1 int,
Player2 int,
Winner int
FOREIGN KEY (Player1) REFERENCES  Players(ID) ON DELETE CASCADE,
FOREIGN KEY (Player2) REFERENCES  Players(ID) ON DELETE CASCADE,
FOREIGN KEY (Winner) REFERENCES  Players(ID) ON DELETE CASCADE
);