CREATE DATABASE TennisScoreboard;
USE TennisScoreboard;

CREATE TABLE Players(
ID int PRIMARY KEY NOT NULL IDENTITY(1,1),
Name varchar(55)
);

CREATE TABLE Matches(
ID int PRIMARY KEY NOT NULL IDENTITY(1,1),
Player1 int,
Player2 int,
Winner int
FOREIGN KEY (Player1) REFERENCES  Players(ID) ON DELETE NO ACTION,
FOREIGN KEY (Player2) REFERENCES  Players(ID) ON DELETE NO ACTION,
FOREIGN KEY (Winner) REFERENCES  Players(ID) ON DELETE NO ACTION
);