version: '3.4'

networks:
  deploy-guide:
    driver: bridge

services:
  tennis:
    image: tennis
    container_name: tennis
    build:
      context: .
      dockerfile: tennis/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - deploy-guide
    depends_on:
      - postgres
    command: ["dotnet", "ef", "database update"]

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pisyakota1
      - POSTGRES_DB=tennis
    ports:
      - "5432:5432"
    networks:
      - deploy-guide
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: